### ISSUE TITLE
Is it alpha or beta or what is the status?

### ISSUE THREAD

**Issue by cherviakovtaskworld** [growthbook/growthbook-cli#27]
So I am working on linux, using firefox, growthbook seems to have only chrome extention to work with so I was looking for alternative, found in growthbook docs there is cli, but surprised to find that there is only 1 command currently supported. Is that alpha or beta or what is the status? I need to work with flags, need to list them need to switch them on/off make them work for specific ids, where is all that and when it going to come?

**Comment by tinahollygb** [comment]
Hi @cherviakovtaskworld, thanks for the question.

To accomplish what you're trying to do, I think using the public REST API is your best option at the moment. [Here are the docs](https://docs.growthbook.io/api/) which you can get to from the main docs site under Platform &rarr; API. We currently have support in the API for [toggling a feature](https://docs.growthbook.io/api/#tag/features/operation/toggleFeature) and getting a [list of feature flags](https://docs.growthbook.io/api/#tag/features/operation/listFeatures). 

There are plans to add this functionality to the CLI. The CLI will heavily leverage the API for most of its functionality, so we need to build that out first. Once we've built out the endpoints more, there are plans to add more functionality to the CLI. You can read about the current functionality of the CLI [here](https://docs.growthbook.io/tools/cli) but you're right, there's only one command at the moment for working with features, and it's to help support type safety in TypeScript projects.

With regards to tools, we currently have the [CLI](https://docs.growthbook.io/tools/cli), a [VSCode extension](https://docs.growthbook.io/tools/vscode-extension) which can be used to view and copy feature flag keys in VSCode, and the [Chrome extension](https://docs.growthbook.io/tools/chrome-extension) with the visual editor.

I'll be closing this issue since it's not related to a feature or a bug, but if you had anymore general questions like this, you are welcome to [join our Slack](https://slack.growthbook.io/?ref=github-growthbook-cli) and ask there were any of our team members would be happy to answer.

**Comment by cherviakovtaskworld** [comment]
Thanks for fast answer, all clear now. Looking forward for cli development in the future, but would advice to specify in this repo README and growthbook docs state of the tools, otherwise it become confusing, say I reading in docs cli available considered it to be as ready as github cli.
